# This file is to store the simulation configuration for smoke simulation
data_save_root: "/media/bamf-big/gefan/DiffFluids/data/smoke"

# Experiment configuration 1
res64x64_dt5e-1_t50_nsrc16_grid:
  resolution_x: 64
  resolution_y: 64
  num_frames: 100
  time_step: 0.5

  num_src_pos_x: 4
  num_src_pos_y: 4

  src_radius: 2
  src_strength: 1

# Experiment configuration 2
res64x64_dt25e-2_t50_nsrc36_grid:
  resolution_x: 64
  resolution_y: 64
  num_frames: 200
  time_step: 0.25

  num_src_pos_x: 6
  num_src_pos_y: 6

  src_radius: 2
  src_strength: 0.5

# Experiment configuration 3
res64x64_dt125e-3_t50_nsrc64_grid:
  resolution_x: 96
  resolution_y: 96
  num_frames: 400
  time_step: 0.125

  num_src_pos_x: 8
  num_src_pos_y: 8

  src_radius: 2
  src_strength: 0.25

# Experiment configuration 4
res64x64_dt1_t100_nsrc3600_random:
  resolution_x: 64
  resolution_y: 64
  num_frames: 100
  time_step: 1
  num_src

  src_radius: 2
  src_strength: 1
