# This file is to store the simulation configuration for smoke simulation

# small simulation, total samples: 1600
small:
  resolution_x: 48
  resolution_y: 64
  num_frames: 100
  time_step: 0.5

  num_src_pos_x: 4
  num_src_pos_y: 4

  data_save_path: '../data/smoke/smoke_small.npz'

  src_radius: 2
  src_strength: 1

# medium simulation, total samples: 7200
medium:
  resolution_x: 64
  resolution_y: 96
  num_frames: 200
  time_step: 0.25

  num_src_pos_x: 6
  num_src_pos_y: 6

  data_save_path: '../data/smoke/smoke_medium.npz'

  src_radius: 2
  src_strength: 0.5

# large simulation, total samples: 25600
large:
  resolution_x: 96
  resolution_y: 128
  num_frames: 400
  time_step: 0.125

  num_src_pos_x: 8
  num_src_pos_y: 8

  data_save_path: '../data/smoke/smoke_large.npz'

  src_radius: 2
  src_strength: 0.25
