dirname: ???    # where the data is stored
experiment: ???
pdeconfig:
  class_path: pde.NavierStokes2D
  init_args:
    tmin: 0.0
    tmax: 50.0
    Lx: 32.0  # the physical size of x
    Ly: 32.0  # the physical size of y
    nt: 500 # number of timesteps at minimum dt
    nx: 128 # spatial resolution on x-axis
    ny: 128 # spatial resolution on y-axis
    skip_nt: 0 # initial timesteps to ignore
    sample_rate: 5 # sampling rate of data as a multiple of minumum dt
    nu: 0.03 # viscosity
    buoyancy_x: 0.0 # bouyancy force in horizontal direction
    buoyancy_y: 1.0 # bouyancy force in vertical direction
    source_ycoord: 5.0
    source_strength: 1.0
    source_radius: 0.5
samples: 68