# This file is to store the configuration for ddpm
dataset:
  name: "NSPointSrcSmoke_resolution_64x64_train.h5"
  root: "/media/bamf-big/gefan/DiffFluids/data/2d_floating_smoke/"

training_params:
  learning_rate: 0.0001
  learning_rate_final: 0.1
  n_epochs: 30
  batch_size: 8
  patience: 20

diffuser:
  n_diffusion_steps: 500
  betas: [0.0001, 0.02]
  
eps_model:
  in_channels: 5
  out_channels: 3
  emb_size: 128
  layer_channels: [32, 64, 128, 256, 512]
  n_groups: 8
  
recording_params:
  eval_interval: 5
  tb_writer_root: "/media/bamf-big/gefan/DiffFluids/diff_fluids/ddpm/logs/"
  model_save_root: "/media/bamf-big/gefan/DiffFluids/diff_fluids/ddpm/checkpoint/"
