# This file is to store the configuration for ddpm
# Normal UNet without cross attention
UNet:
  in_channels: 1
  out_channels: 1
  channels: 32
  channel_multiplers:
    - 1
    - 2
    - 4
    - 8
  n_res_blocks: 2
  attention_levels:
    - 0
    - 1
    - 2
  n_heads: 4
  cond_channels: 3

# A UNet with cross attention
XUNet:
  in_channels: 1
  out_channels: 1
  channels: 32
  channel_multiplers:
    - 1
    - 2
    - 4
    - 8
  n_res_blocks: 2
  attention_levels:
    - 0
    - 1
    - 2
  transformer_layers: 1
  cond_channels: 3